services:
  odb-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olead-board
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - odb-data:/app/data

volumes:
  odb-data:
    driver: local
